### ISSUE TITLE
Selfies are mirrored on iPhone SE, iOS 13.5.1

### ISSUE THREAD

**Issue by maxfreu** [TelegramMessenger/Telegram-iOS#350]
When taking a selfie using the front camera with Telegram 7.0 on an iPhone SE running iOS 13.5.1 my shirts says "ASAN" instead of "NASA" ;-) The normal camera app takes correct photos.

**Comment by laktyushin** [comment]
It's intended. We switched to wysiwyg there after many user complaints. If you need to mirror it you can do so in the crop section of photo editor.

**Comment by maxfreu** [comment]
Strange. I don't see the benefit of taking mirrored pictures. And that's what I currently get from the front camera. The back camera works normally.

**Comment by PauloGDPeixoto** [comment]
There should be a way to set the default for this option, while I understand that  you want to keep mirrored as the default, it's very annoying to go into a sub menu every time I take a photo with telegram in order to make it appear as it should.
For the record, it's also not intuitive at all that this option is hidden with a dubious icon in the crop menu.
