### ISSUE TITLE
Reply button doesn't work on Apple Watch

### ISSUE THREAD

**Issue by lolka4toli** [TelegramMessenger/Telegram-iOS#438]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When user receives a message, notification on Apple Watch appears with two buttons – Reply and Close. The first one doesn't work, there is only animation of tapping.

### Expected Behavior
Ability to use "Reply" button to reply.

### Actual Behavior
No ability to use "Reply" button to reply :)

### Steps to Reproduce
1. Receive a message on Apple Watch
2. Scroll down to Reply button
3. Press the button

### Environment
**Device:** Apple Watch Series 4, 44 mm

**iOS version**: `14.3`

**watchOS version**: `7.2`

**App version:** `7.3.1`

**Comment by electrauuu** [comment]
I can confirm this bug. I have same problem on iOS `14.3` and watchOS `7.2`.

**Comment by matteocef** [comment]
Confirm same issue! Latest update in both!

**Comment by trsrm** [comment]
+1

**Comment by bennijamm** [comment]
+1

**Comment by DevilDimon** [comment]
+1

**Comment by ivmelnik** [comment]
I encountered the same issue just after the latest updates on my iphone 11 + apple watch 5. I thought it was an obvious bug and it would be fixed very soon, but a month had gone and nothing changed. Could you fix it soon please? It is very annoying!

**Comment by mlgy** [comment]
+1
iOS 14.4, watchOS 7.3, app version 7.4.1
Trying delite app both iphone/watch > unpairing watch > restore > install app - nothing.

**Comment by Fulminant** [comment]
+1 
iOS `14.4`, watchOS `7.3`, app version `7.4.1 (build 19850)`.

Seems to have a problem after when the Telegram was updated to version 7.2. On the 7.1.x version reply button works correctly.
Nothing helps, I tried to remove the application on the phone and watch, tried to unpair them, and reset watches completely.

Also, since I saw the bug, I wrote to the support team three times, but they don't respond.

**Comment by lolka4toli** [comment]
7.4.2 – still persists.

**Comment by SebDominguez** [comment]
+1
This bug is really annoying and show how much the WatchOS integration is a really low level priority for this project. I wouldn't be surprised if they drop support completely for the WatchOS soon. Also when you have more than one account the compagnon app take an absurde amount of time to load (more than 30 seconds)

**Comment by mupet0000** [comment]
+1 this is happening to me also. iPhone 11 Pro Max, iOS 14.4. Apple Watch S5 WatchOS 7.3.1.

Reply button doesn’t work and also the entire watch os telegram app shows no conversations or has any function what so ever it’s completely broken.

**Comment by Fulminant** [comment]
Yesterday(02/24/2021) telegram updated to the 7.5 (build 20153) version. The bug finally fixed.

**Comment by lolka4toli** [comment]
Oh my.
