### ISSUE TITLE
Spamming "You have a new message" notifications in Telegram Fork apps.

### ISSUE THREAD

**Issue by maximality** [TelegramMessenger/Telegram-iOS#690]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
Seems like Telegram is designed to send silent notifications on some actions like reading messages on other devices. 
The problem is that they don't really silent (they contain the `mutable-content` property and Notification Service Extension is showing it to a user).
It affects all Telegram iOS Fork Apps I've tested (Nicegram, iMe Messenger, etc.).
There is an entitlement to filter notifications https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering but I don't see it anywhere in Telegram source code. So I'm not sure how do Telegram filter out those notifications.

### Expected Behavior
I think Telegram should send a proper silent push notification like described in Apple Docs so they won't be shown to user:
```
{
   "aps" : {
      "content-available" : 1
   },
   "acme1" : "bar",
   "acme2" : 42
}
```
Or maybe there should be some code to filter out those notifications with `com.apple.developer.usernotifications.filtering` entitlement.

### Actual Behavior
Here is the notification that app is receiving.

**Encrypted:**
```
[AnyHashable("aps"): {
    alert = "You have a new message";
    "mutable-content" = 1;
}, AnyHashable("p"): 65O2dqg5-gh5-MugrAQyYcYtNEjjhDsaN-eZFKTMlvQmdoOVVi0AO3NVPOwmlWv-Kj3_jLtJjDqQ91SH3egNhCTJzZkPXPYvKUAwISSpr1wg21kAKd9uplm8BfnIneUlIklRLsrWJZfbeX6iVBoYNMIBSp9fcd0mzelWz28Khm9noRGwuFeAodsmpwga2faRf1ALSHuBZCXm0v6Tj14jJfX1K-hNJpy0hReJiyAwJHrGDr8moaXBHEJefC_uveRPjI96Zi9tYuEwF6C8P-GXAkmE9C9pFlORxCPH0LCnd3c-aRQeotZ3cQ]
```

**Decrypted:**
```
["aps": {
    "mutable-content" = 1;
}, "chat_id": 305584975, "loc-key": READ_HISTORY, "max_id": 1298558]
```

Which basically is mutable content notification (for Notification Service). 
Then I see the following in logs:
```
Updating content to { title: nil
 subtitle: nil
 body: nil,
 threadId: nil,
 sound: nil,
 badge: nil,
 category: nil,
 userInfo: [:],
 senderImage: empty,
 isLockedMessage: nil,
}
```
For some reason this results to "You have a new message" notification.

### Steps to Reproduce
1. Login to account on multiple devices/apps (one should be the Fork iOS App).
2. Start reading message in the app which is not a fork (for example Mac App).
3. Fork app will show redundant notifications (see the screenshot).

### Screenshots and Videos 
![IMG_EEE14CC7E1CF-1](https://user-images.githubusercontent.com/5983656/147287778-2d609c37-e6db-403a-b0a0-d17c5e268696.jpeg)

### Environment
**Device:** `Any iPhone/iPad`

**iOS version**: `any`

**App version:** `8.3.1`

**Comment by ali-fareed** [comment]
You need to request access to this entitlement with Apple.

**Comment by Rithari** [comment]
> You need to request access to this entitlement with Apple.

I don't understand. The issues was apparently resolved in 8.3.1.22536. 
However, mention of this fix is only found on the bug tracking platform for Telegram. Forks for Telegram still experience he issue, which leads me to believe that they are also in need of the same fix - would you please point us in the correct direction since this was indeed fixed so that we can bring it up to the relevant fork repository? Thank you.

**Comment by WYStudioEx** [comment]
I am a developer of a third-party client, so I need to know how to solve this problem. apns pushed by Telegram service cannot be blocked by code on iOS, which is determined by iOS. It feels like Telegram has certain Settings to notify the server not to push similar apns, rather than the client to deal with, I use Telegram's original code, and then change to other signatures, there will be problems.

Reproduction steps:
1. Log in to your account on multiple devices/apps (one of which should be the Fork iOS app).
2. Read the message in the beginning of one of the applications.
3. The Fork application will receive an update of the unread apns, which removes the problem.

Telegram apns:
{"aps":{"alert":"you have a new message","badge":0,"sound": "default","mutable-content":1}}

**Comment by chechoora** [comment]
This issue occurs because the app lacks the com.apple.developer.usernotifications.filtering entitlement. The original Telegram iOS app uses this entitlement to filter out service-related APNS messages (like badge counter updates and old notification cleanup). Without this entitlement, you'll receive all these background notification updates. Check the [Apple documentation](https://developer.apple.com/documentation/bundleresources/entitlements/com.apple.developer.usernotifications.filtering) for more details on implementing this entitlement.

Right now I am trying to figure out workaround but no luck.
