### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by zats** [TelegramMessenger/Telegram-iOS#730]
Hey folksy, are there any plans to move towards end to end encryption? 
If so mind linking to some RFCs, I was curious to see if I can be helpful

**Comment by alberussoftware** [comment]
What's the point of that? If you want end-to-end encryption, use private chats. For everything else, it is not necessary, because the traffic is encrypted anyway, and the keys are scattered on different servers, yes it is not end-to-end encryption, but it allows to work the main feature of Telegram, which is synchronization between all devices. Private chats can not do this, well, it is understandable.
