### ISSUE TITLE
Tulsi always crashed

### ISSUE THREAD

**Issue by zhangxu0302** [TelegramMessenger/Telegram-iOS#738]
### Checklist
- [ ] I am reporting an issue in existing functionality that does not work as intended
- [ ] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
I followed the tutorial to finish, generated Telegram.tulsiproj, but Tulsi always crashed when using this file to generate Xcode projects.
### Expected Behavior
Use Telegram. tulsiproj to generate Xcode project normally.

### Actual Behavior
Tulsi always crashed.

### Environment
**App verson:**`8.6`

**Bazel version**: `5.0.0`

**Xcode version:** `13.2.1`

**MacOS version:** `12.3`

**Comment by zhangxu0302** [comment]
![image](https://user-images.githubusercontent.com/17900623/159214209-ee4d443b-5150-448a-b0a7-b3186149523e.png)

The figure only generates these three files without Telegram.codeproj file.

**Comment by TimorYang** [comment]
Hey, bro!
I also encountered the same problem, and I found a solution.
Step 1
visit [Tulsi](https://github.com/bazelbuild/tulsi#building)
Step 2
Clone the project and execute `build_and_run.sh` command
Step 3
Use the compiled product **Tulsi** to open `Telegram-iOS/build-input/gen/project/Telegram.tulsiproj`
Step 4
Select the **Configs** column and click the generate button in the lower right corner
Now you can see that the `Telegram-iOS` project has appeared in front of you

**Comment by shivanraptor** [comment]
You are not using the suggested command to generate the Xcode project / build the App. You followed the wrong tutorial. View README.

**Comment by xuchaofei** [comment]
> 
你好，请问一下能用中文说一下吗   看的不是很明白啊   谢谢！

**Comment by shivanraptor** [comment]
> 你好，请问一下能用中文说一下吗 看的不是很明白啊 谢谢！

Learn English.

**Comment by xuchaofei** [comment]
[Info] Running /usr/bin/xcrun swift --version
[Syslog] ** Completed extract_default_swift_version in 0.1281s
[Syslog] ** Completed generating_top_level_build_configs in 0.1305s
[Syslog] ** Completed generating_build_targets in 0.0004s
[Syslog] ** Completed patching_bazel_relative_references in 0.0999s
[Syslog] ** Completed patching_external_repository_references in 0.0000s
[Syslog] ** Completed updating_dbgshellcommands in 0.0033s
2022-06-02 13:46:00.303 Tulsi[1270:21562] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 2'

libc++abi: terminating with uncaught exception of type NSException
Traceback (most recent call last):
  File "/Users/apple/Desktop/Robin/build-system/Make/Make.py", line 646, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/apple/Desktop/Robin/build-system/Make/Make.py", line 396, in generate_project
    generate(
  File "/Users/apple/Desktop/Robin/build-system/Make/ProjectGeneration.py", line 128, in generate
    call_executable([
  File "/Users/apple/Desktop/Robin/build-system/Make/BuildEnvironment.py", line 60, in call_executable
    subprocess.check_call(resolved_arguments, env=resolved_env)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/apple/Desktop/Robin/build-input/gen/project/Tulsi.app/Contents/MacOS/Tulsi', '--', '--verbose', '--genconfig', '/Users/apple/Desktop/Robin/build-input/gen/project/Telegram.tulsiproj:Telegram', '--bazel', '/Users/apple/Desktop/Robin/build-input/gen/project/bazel', '--outputfolder', '/Users/apple/Desktop/Robin/build-input/gen/project', '--no-open-xcode']' died with <Signals.SIGABRT: 6>.
Environment
App verson:8.6

Bazel version: 5.0.0

Xcode version: 13.2.1

MacOS version: 12.4
How can i to fix it? thanks
