### ISSUE TITLE
[Feature Request] Disable quick reaction

### ISSUE THREAD

**Issue by Jiraffe7** [TelegramMessenger/Telegram-iOS#808]
There is no way to disable quick reactions (double tap on a message to send a reaction).

The addition of this feature has removed the ability to double tap a message as a quicker equivalent to long-pressing a message. This functionality still exists in groups with reactions disabled, so I would like an option to disable quick reactions.

I am willing to contribute and implement this feature, if someone could guide me on the process (I don't see a CONTRIBUTING.md)

**Comment by shivanraptor** [comment]
You can edit the codes and submit a pull request

**Comment by ali-fareed** [comment]
The relevant condition is checked here: https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/TelegramUI/Sources/ChatMessageBubbleItemNode.swift#L3110

I can add an option to the debug menu, but I suggest you just get used to the new behavior. Long tap gesture works with every message type.

**Comment by Jiraffe7** [comment]
@ali-fareed Thanks for the reply! I'm not familiar with Swift and the codebase, so I don't know how difficult it is to add a "None" option to the quick reactions menu and propagate that in the condition check?

Given that it's been a long time since this feature was added, we've had no choice but to get used to the new behaviour. But it's something that people want: https://bugs.telegram.org/?sort=rate&query=quick%20reactions

Some reasons for wanting to disable quick reactions:
1. It's faster and consistent to double tap a message to open the context menu. (my main use-case)
2. People were used to double-tapping to open the context menu, and this feature affected their muscle memory.
3. A little philosophical but quick reactions are not valuable "messages" for conveying anything and they add to notification noise, especially since there is no way to disable reaction notifications yet.

**Comment by LWChris** [comment]
I would also like to disable quick reactions, I quite often accidentally trigger them by tapping the message when I try to scroll. I am not using reactions anyway since it's not really faster to select it from the "quick" wheel instead of just sending the emoji from the emoji keyboard or simply writing "okay", "nice" or "oh no".

**Comment by utsavDave97** [comment]
@ali-fareed @shivanraptor Do you guys think we need this? I can contribute to this. Please let me know. Appreciate it.

**Comment by StarHack** [comment]
Quick reactions are a little tedious. I trigger them accidentally quite often and I get notified because someone put a thumbs up on an old message, so there probably should be options to:

- Disable the double tap feature
- Remove reactions from the entire UI to make conversations more readable

**Comment by LWChris** [comment]
I understand what reactions are meant to be for, but right now they are a little bit too forced on the user. Instead of simply re-assigning a gesture that previously did something different (double tap was "context menu", now is "react"), there should always be at least the option to select what the gesture does.

Personally, I don't use reactions at all (at least not intentionally, I do use them accidentally quite often), meaning I wouldn't mind not having access to them, so for me, said configuration option works as well as a simple slider to disable (sending) reactions altogether from all places and in all forms of chats.

(Side note, I am an Android user, but I hope if things are bettered in the iOS app, then Android devs might be more willing to make a move, too.)

**Comment by onefreddy** [comment]
Hey guys, please upvote https://bugs.telegram.org/c/12966

**Comment by ali-fareed** [comment]
@utsavDave97 
> @ali-fareed @shivanraptor Do you guys think we need this? I can contribute to this. Please let me know. Appreciate it.

If you a pull request that includes a **debug** option to disable quick reactions, and it doesn't break anything, it will get merged.

**Comment by onefreddy** [comment]
@utsavDave97 I think we really need it, and moreover, we need it for all platforms desktop, mac, android etc

**Comment by ali-fareed** [comment]
@utsavDave97 The option should only be accessible from the hidden menu (10 quick taps on the Settings tab).

To run the app on a real device you will need to generate several provisioning profiles. For an issue such as this one, I suggest to use the simulator-only setup that works out of the box.

**Comment by utsavDave97** [comment]
> @utsavDave97 The option should only be accessible from the hidden menu (10 quick taps on the Settings tab).
> 
> To run the app on a real device you will need to generate several provisioning profiles. For an issue such as this one, I suggest to use the simulator-only setup that works out of the box.

Got it. Thanks.

**Comment by utsavDave97** [comment]
@ali-fareed Created the PR https://github.com/TelegramMessenger/Telegram-iOS/pull/868

**Comment by UnsignedInt8** [comment]
quick reaction is sooooooooooooooo anonying!!!!!!!!!!

**Comment by Draxial** [comment]
Any chance we could get this on android as well? I keep pressing the quick reaction by mistake with my thick fingers, and quickly scrambling to undo the reaction lol

**Comment by 3rd3** [comment]
For those looking for a way to disable quick reactions or double-tap reactions:

* Tap on the settings button 10 times to access the hidden debug menu
* Scroll down all the way
* Disable "Enable Quick Reaction"
