### ISSUE TITLE
No markdown menu

### ISSUE THREAD

**Issue by ttyport** [TelegramMessenger/Telegram-iOS#817]
### Description
No markdown menu when selecting text

### Environment
**Device:** `iPhone 12 Pro`

**iOS version**: `16.0`

**App version:** `8.8.3`

**Comment by LottoLemons** [comment]
Experiencing the same problem. Although I'm pretty sure it's an iOS problem, since it doesn't show  up in WhatsApp either

**Comment by Kamik423** [comment]
This occurred simultaneously with iOS / iPadOS 16. And it should really be fixed before release. If the `BIU` icon is broken from Apple‘s side you should still have some replacement (like a plain text button labeled `BIU` or `Markup`) since people **do actively use this**.

I miss this every day. I can still do some markup with the plain text controls but not links, which is frustrating. And I can also not remove any markup when editing a message. Please add a hot fix!

**Comment by GreenYun** [comment]
On iOS 16, apps should adopt `UIEditMenuInteraction` instead of `UIMenuController` for the edit box.

Reference: 
1. https://developer.apple.com/documentation/uikit/uieditmenuinteraction
2. https://developer.apple.com/videos/play/wwdc2022/10071/

**Comment by ali-fareed** [comment]
Fixed in 9.0.1.
