### ISSUE TITLE
What should be demo account credentials for App store connect?

### ISSUE THREAD

**Issue by bkg866** [TelegramMessenger/Telegram-iOS#938]
I have submitted a reproducible Telegram build to the app store but they are unable to review it because they want Demo account credentials to test the application.

Is there a way to give test access as a test user account to the apple review team to enter a test phone number and a code to sign in to the app and test features? Even if it is a dummy user it works for us.

Thanks in advance for any suggestions/recommendations.

For more information please see attached screenshot.
![WhatsApp Image 2022-12-18 at 7 04 49 PM](https://user-images.githubusercontent.com/7617835/208301350-f8cd5614-d1da-4f20-80d1-bfecbe354e89.jpeg)

![Screen Shot 2022-12-16 at 8 48 32 pm](https://user-images.githubusercontent.com/7617835/208251139-0203842d-8ce0-43b9-b6dd-5632cc3d5835.png)

**Comment by johndpope** [comment]
This ticket helps - https://github.com/TelegramMessenger/Telegram-iOS/issues/938

but how can apple bypass the need for phone number using test?

**Comment by bkg866** [comment]
@laktyushin can you help on this please

**Comment by johndpope** [comment]
UPDATE - 
apple are repeatedly blocking app due to no demo credentials - even though we've told them they need a phone number.

I'm investigating feasibility of injecting an existing hard coded session given a known demo phone number.
foreseeably - the pin code will be bypassed - and I want to resurrect a session from archived session.
any tips / pointers would be helpful here. I can see the active sessions - but presumably this is not reflecting the necessary headers / tokens needed to access api. 
 
<img width="1295" alt="Screenshot 2022-12-27 at 10 06 44 am" src="https://user-images.githubusercontent.com/289994/209599786-e07277c2-e1cc-4d40-b84a-e34fd8604902.png">

**Comment by Kylmakalle** [comment]
See Telegram docs on test accounts 
https://core.telegram.org/api/auth#test-accounts

**Comment by johndpope** [comment]
Thanks @Kylmakalle 
we need a toggle switch in settings to set test. 
seems like you can only toggle (10 presses on settings tab) by being logged in.
<img width="465" alt="Screenshot 2022-12-27 at 6 04 36 pm" src="https://user-images.githubusercontent.com/289994/209733158-52f1038f-c4c1-47f3-9a23-aff888566310.png">

**Comment by Kylmakalle** [comment]
To make it work, you should expose the test environment switch or determine it by the number of users provided. It can be done in [AuthorizationSequencePhoneEntryController.swift](https://github.com/TelegramMessenger/Telegram-iOS/blob/master/submodules/AuthorizationUI/Sources/AuthorizationSequencePhoneEntryController.swift#L254)

In this example, If the user types the number "0000000000" with any country code, we will switch to the test backend and offer a new login window.

```swift
@objc func nextPressed() {
        let (_, _, number) = self.controllerNode.codeAndNumber
        if !number.isEmpty {
        /* ... */
        if (number == "0000000000") {
            self.sharedContext.beginNewAuth(testingEnvironment: true)
            self?.back()
            return
        }
```

P.S. Treat this example as a pseudocode. I've been leveraging a similar method in the older Telegram sources version.

**Comment by johndpope** [comment]
perfect
